import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { FadeUp, StaggerGroup, StaggerItem } from "@/components/Motion";
import { PROJECTS, PROJECT_GROUPS } from "@/lib/site-data";
import { OPERATIONAL_PROJECTS, OPERATIONAL_PROJECT_GROUPS } from "@/lib/project-additions";

const ALL_PROJECTS=[...OPERATIONAL_PROJECTS,...PROJECTS];
const ALL_GROUPS=Array.from(new Set([...OPERATIONAL_PROJECT_GROUPS,...PROJECT_GROUPS]));

export default function Projects(){return <>
<section className="relative pt-24 md:pt-32 pb-12 overflow-hidden bg-[#F3F1EB] border-b border-[#111]/10" data-testid="projects-hero"><div className="container-x"><FadeUp><div className="eyebrow mb-5">Selected systems</div><div className="grid lg:grid-cols-12 gap-8 items-end"><h1 className="lg:col-span-8 text-[38px] md:text-[54px] lg:text-[64px] leading-[1.02] tracking-[-0.035em] font-medium max-w-[900px]">Custom software for the workflows where <span className="text-[#1689C9]">time and money get stuck.</span></h1><p className="lg:col-span-4 text-[16px] md:text-[17px] text-[#555] leading-relaxed">Each project below uses a different operational interface language based on the actual problem — not a repeated decorative thumbnail.</p></div></FadeUp></div></section>
<section className="py-16 md:py-24" data-testid="projects-grid"><div className="container-x space-y-20">{ALL_GROUPS.map(group=>{const items=ALL_PROJECTS.filter(p=>p.vertical===group);if(!items.length)return null;return <div key={group}><FadeUp><div className="flex items-center gap-4 mb-8"><h2 className="text-[22px] md:text-[26px] font-medium tracking-tight">{group}</h2><div className="flex-1 h-px bg-[#D9D9D4]"/><span className="font-mono text-[10px] uppercase tracking-[.16em] text-[#999]">{items.length} systems</span></div></FadeUp><StaggerGroup className="grid md:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-12">{items.map(p=><StaggerItem key={p.slug}><ProjectCard project={p}/></StaggerItem>)}</StaggerGroup></div>})}</div></section>
<section className="pb-28"><div className="container-x text-center"><FadeUp><h2 className="text-[36px] md:text-[52px] tracking-[-0.03em] leading-[1.05] max-w-[820px] mx-auto">Show us the expensive workflow. We’ll design the operating layer around it.</h2><Link to="/contact" className="btn-primary mt-8">Book an operations AI call <ArrowRight className="w-4 h-4"/></Link></FadeUp></div></section>
</>}

function ProjectCard({project}){return <Link to={`/projects/${project.slug}`} className="group block h-full"><ProjectThumbnail project={project}/><div className="pt-5"><div className="font-mono text-[9px] uppercase tracking-[.16em] text-[#777]">{project.vertical}</div><h3 className="mt-2 text-[21px] md:text-[24px] font-medium leading-[1.12] tracking-[-0.025em]">{project.name}</h3><p className="mt-3 text-[14px] text-[#5B5B5B] leading-relaxed line-clamp-3">{project.summary}</p><span className="mt-4 inline-flex items-center gap-1.5 text-[#1689C9] text-[13px]">See workflow <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform"/></span></div></Link>}

function ProjectThumbnail({project}){return <div className="relative aspect-[16/10] overflow-hidden bg-[#ECE9E1] border border-[#111]/12 group-hover:-translate-y-1 transition-transform duration-300"><Visual project={project}/></div>}

function Visual({project}){const s=project.slug;
if(s==="production-planning-control-tower")return <Gantt/>;
if(s==="warehouse-inventory-control")return <Warehouse/>;
if(s==="procurement-rfq-intelligence"||s==="sourcedesk")return <Procurement/>;
if(s==="predictive-maintenance-reliability"||s==="factory-os")return <Maintenance/>;
if(s==="quality-ncr-capa-platform")return <Quality/>;
if(s==="industrial-document-control")return <Documents/>;
if(s==="oilfield-job-readiness")return <Oilfield/>;
if(s==="cross-functional-operations-os")return <ControlTower/>;
if(/fleet|logistics/i.test(s))return <Fleet/>;
if(/safety|thermal|emission/i.test(s))return <Vision/>;
if(/clinic|dental|sukhya|health/i.test(s))return <Healthcare/>;
if(/nainley|quiet|v7/i.test(s))return <Commerce/>;
if(/pico|apex|sansai/i.test(s))return <AgencyOps/>;
return <ControlTower/>}

const Shell=({label,children,dark=false})=><div className={`absolute inset-0 p-4 md:p-5 ${dark?'bg-[#10110f] text-white':'bg-[#F1EEE7] text-[#111]'}`}><div className="flex justify-between font-mono text-[8px] uppercase tracking-[.15em] opacity-45"><span>{label}</span><span>NA / LIVE</span></div>{children}</div>;
function Gantt(){return <Shell label="Production planning"><div className="mt-5 grid grid-cols-[80px_1fr] gap-2 text-[8px]"><div className="space-y-3 pt-2">{["Line A","Line B","CNC-04","Assembly","QA"].map(x=><div key={x}>{x}</div>)}</div><div className="relative h-[150px] border-l border-t border-[#111]/15 bg-white/45">{[[12,38,1],[40,72,2],[18,58,3],[60,90,4],[32,82,5]].map(([l,r,i])=><div key={i} className="absolute h-4 bg-[#1689C9]" style={{left:`${l}%`,width:`${r-l}%`,top:`${i*26-15}px`}}/>)}<div className="absolute top-0 bottom-0 left-[68%] w-px bg-[#C94B3A]"/></div></div><div className="absolute bottom-4 left-4 right-4 grid grid-cols-3 gap-2 text-[8px]"><Stat a="OTD risk" b="6 jobs"/><Stat a="Bottleneck" b="CNC-04"/><Stat a="Material" b="2 short"/></div></Shell>}
function Warehouse(){return <Shell label="Warehouse control"><div className="mt-5 grid grid-cols-6 gap-1 h-[135px]">{Array.from({length:18}).map((_,i)=><div key={i} className={`border ${[4,9,15].includes(i)?'bg-[#F5D0C8] border-[#C94B3A]/30':'bg-[#D7ECF6] border-[#1689C9]/20'} relative`}><span className="absolute bottom-1 left-1 text-[7px] opacity-45">Z{i+1}</span></div>)}</div><div className="absolute bottom-4 left-4 right-4 grid grid-cols-3 gap-2 text-[8px]"><Stat a="Inbound" b="94.2%"/><Stat a="Exceptions" b="17"/><Stat a="Slow stock" b="₹18.4L"/></div></Shell>}
function Procurement(){return <Shell label="Procurement / RFQ"><div className="mt-8 flex items-center gap-2">{["Need","RFQ","3 quotes","Compare","Approve","PO"].map((x,i)=><div key={x} className={`flex-1 min-h-[90px] border p-2 flex flex-col justify-between ${i===3?'bg-[#1689C9] text-white border-[#1689C9]':'bg-white/65 border-[#111]/15'}`}><span className="text-[7px] opacity-50">0{i+1}</span><span className="text-[9px]">{x}</span></div>)}</div><div className="absolute bottom-4 left-4 right-4 h-8 bg-white/60 border border-[#111]/10 flex items-center px-3 text-[8px] gap-4"><span>Best landed cost</span><b>Vendor B</b><span className="ml-auto text-[#1689C9]">−7.8%</span></div></Shell>}
function Maintenance(){return <Shell label="Reliability intelligence" dark><div className="mt-5 grid grid-cols-12 gap-3 h-[155px]"><div className="col-span-8 border border-white/12 p-3 relative"><div className="text-[8px] opacity-45">VIBRATION / ASSET P-104</div><svg viewBox="0 0 260 90" className="absolute left-3 right-3 bottom-3 w-[92%] h-[70%]"><polyline points="0,72 25,69 48,67 70,62 95,65 120,50 145,54 170,40 195,46 220,27 260,17" fill="none" stroke="#72c8ef" strokeWidth="3"/><line x1="0" y1="45" x2="260" y2="45" stroke="rgba(255,255,255,.2)" strokeDasharray="5 5"/></svg></div><div className="col-span-4 space-y-2"><StatDark a="Risk" b="82%"/><StatDark a="Window" b="4–7 d"/><StatDark a="Spare" b="Bearing"/></div></div></Shell>}
function Quality(){return <Shell label="Quality / NCR / CAPA"><div className="mt-6 grid grid-cols-2 gap-3 h-[150px]"><div className="bg-white/65 border border-[#111]/10 p-3"><div className="text-[8px] opacity-45">DEFECT TREND</div><div className="mt-6 flex items-end gap-2 h-[85px]">{[28,62,38,74,52,31].map((h,i)=><div key={i} className="flex-1 bg-[#1689C9]/25 border-t-2 border-[#1689C9]" style={{height:`${h}%`}}/>)}</div></div><div className="bg-[#111] text-white p-3"><div className="text-[8px] opacity-45">CAPA QUEUE</div>{["Supplier root cause","Process correction","Closure evidence"].map((x,i)=><div key={x} className="mt-4 pb-2 border-b border-white/15 flex justify-between text-[8px]"><span>{x}</span><span className="text-[#72c8ef]">0{i+2}</span></div>)}</div></div></Shell>}
function Documents(){return <Shell label="Industrial document control"><div className="mt-5 flex justify-center items-center h-[165px]"><div className="w-[58%] h-[145px] bg-white border border-[#111]/10 shadow-sm p-4 -rotate-2"><div className="w-1/3 h-2 bg-[#111]/70"/><div className="mt-4 space-y-2">{[90,75,82,60,88].map((w,i)=><div key={i} className="h-1.5 bg-[#D8D8D3]" style={{width:`${w}%`}}/>)}</div></div><div className="-ml-7 mt-7 bg-[#1689C9] text-white w-[120px] p-3 shadow-lg"><div className="text-[7px] opacity-60">EXTRACTED</div><div className="mt-2 text-[10px]">12 fields</div><div className="text-[10px]">2 exceptions</div></div></div></Shell>}
function Oilfield(){return <Shell label="Oilfield job readiness" dark><div className="mt-7 grid grid-cols-5 gap-2">{[["Scope","100%"],["Materials","82%"],["Equipment","94%"],["Crew","76%"],["Docs","88%"]].map(([a,b],i)=><div key={a} className="border border-white/12 min-h-[105px] p-2 flex flex-col justify-between"><span className="text-[7px] opacity-40">0{i+1}</span><div><div className="text-[8px] opacity-55">{a}</div><div className="text-[16px] mt-1">{b}</div></div></div>)}</div><div className="absolute bottom-4 left-4 right-4 border border-[#C94B3A]/40 bg-[#C94B3A]/15 p-2 text-[8px]">Blocker: Crew certification expires before mobilisation</div></Shell>}
function ControlTower(){return <Shell label="Cross-functional operations OS"><div className="mt-7 grid grid-cols-4 gap-2">{["Sales","Engineering","Procurement","Production","Quality","Dispatch","Finance","Management"].map((x,i)=><div key={x} className={`min-h-[64px] p-2 border text-[8px] flex items-end ${i===7?'bg-[#1689C9] text-white border-[#1689C9]':'bg-white/65 border-[#111]/10'}`}>{x}</div>)}</div><div className="absolute bottom-4 left-4 right-4 h-px bg-[#1689C9]"/></Shell>}
function Fleet(){return <Shell label="Fleet / logistics control"><div className="mt-5 grid grid-cols-3 gap-3"><div className="col-span-2 h-[145px] bg-[#DCEBF1] relative overflow-hidden"><svg viewBox="0 0 260 150" className="w-full h-full"><path d="M10 120 C55 90,80 120,115 80 S175 40,245 58" fill="none" stroke="#1689C9" strokeWidth="3" strokeDasharray="5 5"/><circle cx="75" cy="105" r="7" fill="#111"/><circle cx="158" cy="62" r="7" fill="#111"/><circle cx="230" cy="57" r="7" fill="#1689C9"/></svg></div><div className="space-y-2"><Stat a="On time" b="91%"/><Stat a="At risk" b="6"/><Stat a="ETA" b="14:40"/></div></div></Shell>}
function Vision(){return <Shell label="AI vision / safety"><div className="mt-5 h-[160px] bg-[#1A1A18] relative overflow-hidden"><div className="absolute inset-0 opacity-30" style={{backgroundImage:'linear-gradient(90deg,transparent 49%,#fff 50%,transparent 51%),linear-gradient(transparent 49%,#fff 50%,transparent 51%)',backgroundSize:'50px 50px'}}/><div className="absolute left-[18%] top-[24%] w-[27%] h-[48%] border-2 border-[#72c8ef]"/><div className="absolute right-[12%] top-[38%] w-[22%] h-[35%] border-2 border-[#C94B3A]"/><div className="absolute bottom-3 left-3 text-white text-[8px]">PPE 97.4% · 1 active alert</div></div></Shell>}
function Healthcare(){return <Shell label="Healthcare workflow"><div className="mt-5 grid grid-cols-3 gap-2"><div className="col-span-2 bg-white/70 border border-[#111]/10 h-[150px] p-3"><div className="text-[8px] opacity-45">PATIENT FLOW</div>{["Intake","Consult","Follow-up","Billing"].map((x,i)=><div key={x} className="mt-3 flex items-center gap-2 text-[8px]"><span className="w-5 h-5 rounded-full bg-[#1689C9]/15 flex items-center justify-center">{i+1}</span><div className="flex-1 h-px bg-[#111]/15"/><span>{x}</span></div>)}</div><div className="space-y-2"><Stat a="Waiting" b="08"/><Stat a="Today" b="34"/><Stat a="Follow-up" b="12"/></div></div></Shell>}
function Commerce(){return <Shell label="Commerce operations"><div className="mt-5 grid grid-cols-4 gap-2"><div className="col-span-3 bg-white/70 border border-[#111]/10 h-[150px] p-3"><div className="text-[8px] opacity-45">ORDER / RETENTION</div><div className="mt-5 flex items-end gap-2 h-[90px]">{[38,48,62,55,79,73,91,84].map((h,i)=><div key={i} className="flex-1 bg-[#1689C9]/30" style={{height:`${h}%`}}/>)}</div></div><div className="space-y-2"><Stat a="Orders" b="184"/><Stat a="NDR" b="7"/><Stat a="Recovered" b="₹42k"/></div></div></Shell>}
function AgencyOps(){return <Shell label="Marketing / ops intelligence" dark><div className="mt-6 grid grid-cols-2 gap-3 h-[150px]"><div className="border border-white/12 p-3"><div className="text-[8px] opacity-45">CAMPAIGN MIX</div><div className="mt-5 grid grid-cols-2 gap-2">{["Meta","Google","CRM","Creative"].map((x,i)=><div key={x} className="h-11 bg-white/[.06] border border-white/10 p-2 text-[8px] flex items-end">{x}</div>)}</div></div><div className="border border-white/12 p-3"><div className="text-[8px] opacity-45">INSIGHT</div><div className="mt-5 text-[18px] leading-tight">Creative B is driving 31% lower CAC.</div><div className="mt-5 text-[8px] text-[#72c8ef]">Shift spend →</div></div></div></Shell>}
const Stat=({a,b})=><div className="bg-white/65 border border-[#111]/10 p-2"><div className="text-[7px] opacity-45">{a}</div><div className="mt-1 text-[12px]">{b}</div></div>;
const StatDark=({a,b})=><div className="border border-white/12 p-2"><div className="text-[7px] opacity-45">{a}</div><div className="mt-1 text-[13px]">{b}</div></div>;
